# Sourced from ROME's known_1000 dataset

FACT_BANK = [
    ('The headquarter of Army of the Guardians of the Islamic Revolution is in', ' Tehran'),
    ('Eavan Boland was born in', ' Dublin'),
    ('The capital of Roman Republic is', ' Rome'),
    ('Henri Debain was born in', ' Paris'),
    ('Knud, Hereditary Prince of Denmark passed away in', ' Copenhagen'),
    ('The location of Massachusetts Institute of Technology is in', ' Cambridge'),
    ("Philippines's capital,", ' Manila'),
    ('The location of Galatasaray University is in the heart of', ' Istanbul'),
    ("Grand Duchy of Finland's capital,", ' Helsinki'),
    ("Vichy France's capital,", ' Paris'),
    ('John Pym died in the city of', ' London'),
    ('Swedish Orphan Biovitrum is headquartered in', ' Stockholm'),
    ('Nicolas Gigault was born in', ' Paris'),
    ('Emilia Rydberg was born in', ' Stockholm'),
    ('Joseph Goebbels worked in the city of', ' Berlin'),
    ("Italy's capital,", ' Rome'),
    ('The headquarter of Lokalbahn AG is in the city of', ' Munich'),
    ('2005 Southeast Asian Games is in full swing in the', ' Philippines'),
    ("The capital city of People's Republic of Poland is", ' Warsaw'),
    ('Francesco Castellacci was born in', ' Rome'),
    ('2005 Australian Open is located in', ' Melbourne'),
    ('Giulio Romano originates from the city of', ' Rome'),
    ("Euromoney Institutional Investor's headquarters are in", ' London'),
    ("Metropolitan France's capital,", ' Paris'),
    ('The location of Hungarian Ladies Open is in the heart of', ' Budapest'),
    ("Egypt's capital,", ' Cairo'),
    ('Coco Chanel passed away in', ' Paris'),
    ('The headquarter of Zillow is in downtown', ' Seattle'),
    ('Jan Swammerdam died in the city of', ' Amsterdam'),
    ("Seiyu Group's headquarters are in", ' Tokyo'),
    ('Madame de Montesson died in the city of', ' Paris'),
    ("Second French Empire's capital city is", ' Paris'),
    ('Henry Somerset, 7th Duke of Beaufort worked in the city of', ' London'),
    ("King Chulalongkorn Memorial Hospital's headquarters are in", ' Bangkok'),
    ('York University can be found in the heart of', ' Toronto'),
    ('The capital city of United Kingdom of the Netherlands is', ' Amsterdam'),
    ('The capital city of Kingdom of Hungary is', ' Budapest'),
    ('Rudolf Steiner worked in the city of', ' Berlin'),
    ('James Northcote died in the city of', ' London'),
    ('2002 Australian Open is located in', ' Melbourne'),
    ('Hugh Cairns, 1st Earl Cairns worked in the city of', ' London'),
    ('Louis XVII of France died in the city of', ' Paris'),
    ('Fantastic Fest can be found in the heart of downtown', ' Austin'),
    ('The capital of West Pakistan is', ' Karachi'),
    ('The headquarter of Smith & Wesson is in', ' Springfield'),
]
